
source ~/.vim/appearance.vim
source ~/.vim/encoding_syntax.vim
source ~/.vim/plugins.vim
source ~/.vim/nerdtree.vim
source ~/.vim/ale.vim
source ~/.vim/editor.vim
source ~/.vim/mappings.vim

" --- End of Modular Configuration ---

" You can add any temporary or highly general settings here if needed,
" but prefer adding them to the appropriate modular file.

" Ensure Vim-Plug is installed and plugins are loaded
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Automatically source vimrc if it's changed
augroup MyVimrcEdit
    autocmd!
    autocmd BufWritePost .vimrc,.vimrc.local,vimrc,init.vim,*.vim source $MYVIMRC | echo "Reloaded " . $MYVIMRC
augroup END
