
source ~/.vim/appearance.vim
source ~/.vim/encoding_syntax.vim
source ~/.vim/plugins.vim
source ~/.vim/nerdtree.vim
source ~/.vim/ale.vim
source ~/.vim/editor.vim
source ~/.vim/mappings.vim

" --- End of Modular Configuration ---

" You can add any temporary or highly general settings here if needed,
" but prefer adding them to the appropriate modular file.

" Ensure Vim-Plug is installed and plugins are loaded
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Automatically source vimrc if it's changed
augroup MyVimrcEdit
    autocmd!
    autocmd BufWritePost .vimrc,.vimrc.local,vimrc,init.vim,*.vim source $MYVIMRC | echo "Reloaded " . $MYVIMRC
augroup END

" Loading vim-lsp with minpac:
" call minpac#add("prabirshrestha/vim-lsp")
" ...or use your package manager of choice/Vim native packages

" Useful for debugging vim-lsp:
" let g:lsp_log_verbose = 1
" let g:lsp_log_file = expand('~/vim-lsp.log')




let g:lsp_log_verbose = 1
let g:lsp_log_file = expand('~/vim-lsp.log')

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"

if executable('pylsp')
    " pip install python-lsp-server
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pylsp',
        \ 'cmd': {server_info->['pylsp']},
        \ 'allowlist': ['python'],
        \ })
endif


" Configure as the elixir language server
if executable("elixir")
  augroup lsp_elixir_setup
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'expert',
          \ 'cmd': [expand('~/.vim/lsp/expert_darwin_arm64'), '--stdio'],
           \ 'workspace_config': {'root_uri': '/Users/ambaschobsanti/Developer/learn/Elixir/test_mix'},
          \ 'allowlist': ['elixir', 'eelixir'],
          \ })
    autocmd FileType elixir setlocal omnifunc=lsp#complete
    autocmd FileType eelixir setlocal omnifunc=lsp#complete
  augroup END
endif

" Configure Swift language server (sourcekit-lsp)
let s:sourcekit_lsp_cmd = ''

if executable('sourcekit-lsp')
  let s:sourcekit_lsp_cmd = 'sourcekit-lsp'
else
  " Fallback: check Xcode toolchain path
  let s:xcode_path = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/sourcekit-lsp'
  if filereadable(s:xcode_path)
    let s:sourcekit_lsp_cmd = s:xcode_path
  endif
endif

if !empty(s:sourcekit_lsp_cmd)
  augroup lsp_swift_setup
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'sourcekit-lsp',
          \ 'cmd': {server_info->[s:sourcekit_lsp_cmd]},
          \ 'allowlist': ['swift'],
          \ })
    autocmd FileType swift setlocal omnifunc=lsp#complete
  augroup END
endif

" Configure TypeScript/JavaScript language server
if executable('typescript-language-server')
  augroup lsp_typescript_setup
    autocmd!
    autocmd User lsp_setup call lsp#register_server({
          \ 'name': 'typescript-language-server',
          \ 'cmd': {server_info->['typescript-language-server', '--stdio']},
          \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), ['package.json', 'tsconfig.json', 'jsconfig.json', '.git']))},
          \ 'allowlist': ['javascript', 'javascriptreact', 'typescript', 'typescriptreact'],
          \ })
    autocmd FileType javascript,javascriptreact,typescript,typescriptreact setlocal omnifunc=lsp#complete
  augroup END
endif

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)

    " Note: Ctrl+f and Ctrl+d are preserved for default vim scrolling
    " Use Ctrl+e and Ctrl+y for fine scrolling in LSP hover windows if needed

    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for buffers that have LSP enabled
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
